Repository I3-Project/Delivery_Service, pull requests merged in 2024-11, with the labels that each got.

#14 Fix: 버그 수정 및 유저 연동 작업
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreInfoResponseDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationRequestDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationResponseDto.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement

#17 Feature product
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/product/dto/ProductRegistrationRequestDto.java
  src/main/java/com/i3/delivery/domain/product/dto/ProductRegistrationResponseDto.java
  src/main/java/com/i3/delivery/domain/product/entity/Product.java
  src/main/java/com/i3/delivery/domain/product/enums/ProductStatus.java
  src/main/java/com/i3/delivery/domain/product/repository/ProductRepository.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreEditResponseDto.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
  src/main/java/com/i3/delivery/global/BaseEntity.java
Labels: enhancement

#18 Feat: Product 정보 조회 기능 구현
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/product/dto/ProductInfoResponseDto.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
Labels: enhancement

#19 Feat: Product 수정 조회 기능 구현
  src/main/java/com/i3/delivery/domain/category/controller/CategoryController.java
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/product/dto/ProductEditRequestDto.java
  src/main/java/com/i3/delivery/domain/product/dto/ProductEditResponseDto.java
  src/main/java/com/i3/delivery/domain/product/entity/Product.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
Labels: enhancement

#20 Feat: Product 삭제 기능 구현
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/product/entity/Product.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
Labels: enhancement

#21 Fix : Controller 권한 체크 수정 및 기능 버그 수정 (등록, 수정)
  src/main/java/com/i3/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/i3/delivery/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/i3/delivery/domain/review/entity/Review.java
  src/main/java/com/i3/delivery/domain/review/service/ReviewService.java
Labels: bug

#22 Feature review
  src/main/java/com/i3/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/i3/delivery/domain/review/entity/Review.java
  src/main/java/com/i3/delivery/domain/review/repository/ReviewRepository.java
  src/main/java/com/i3/delivery/domain/review/service/ReviewService.java
Labels: enhancement

#23 Feat: Store, Product 전체조회 API Pageable 적용
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreEditRequsetDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreEditResponseDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreInfoResponseDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationRequestDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreRegistrationResponseDto.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreReviewResponseDto.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement

#25 Feat: Store, Product 리뷰 조회 API Pageable 적용
  src/main/java/com/i3/delivery/domain/product/controller/ProductController.java
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement

#26 Feat: Product AI API 연동 기능 구현
  build.gradle
  src/main/java/com/i3/delivery/domain/product/Ai/GeminiRequest.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
Labels: enhancement

#28 Feat: Global 에러 처리 및 ApiResponse 기능 구현
  src/main/java/com/i3/delivery/global/exception/category/AlreadyExistCategoryException.java
  src/main/java/com/i3/delivery/global/exception/category/CategoryNotFoundException.java
  src/main/java/com/i3/delivery/global/exception/common/AuthorizationException.java
  src/main/java/com/i3/delivery/global/exception/common/BusinessException.java
  src/main/java/com/i3/delivery/global/exception/common/ErrorCode.java
  src/main/java/com/i3/delivery/global/exception/common/GlobalExceptionHandler.java
  src/main/java/com/i3/delivery/global/exception/common/UnAuthorizedModifyException.java
  src/main/java/com/i3/delivery/global/exception/jwt/ExpiredJwtTokenException.java
  src/main/java/com/i3/delivery/global/exception/jwt/InvalidJwtException.java
  src/main/java/com/i3/delivery/global/exception/jwt/InvalidJwtSignatureException.java
  src/main/java/com/i3/delivery/global/exception/jwt/InvalidRefreshTokenException.java
  src/main/java/com/i3/delivery/global/exception/jwt/JwtInvalidException.java
  src/main/java/com/i3/delivery/global/exception/jwt/NoJwtException.java
  src/main/java/com/i3/delivery/global/exception/jwt/UnsupportedGrantTypeException.java
  src/main/java/com/i3/delivery/global/exception/jwt/UnsupportedJwtTokenException.java
  src/main/java/com/i3/delivery/global/exception/product/ProductNotFoundException.java
  src/main/java/com/i3/delivery/global/exception/response/ApiResponse.java
  src/main/java/com/i3/delivery/global/exception/store/StoreNotFoundException.java
Labels: enhancement

#29 Feature payment
  src/main/java/com/i3/delivery/domain/order/entity/enums/OrderStatusEnum.java
  src/main/java/com/i3/delivery/domain/payment/controller/PaymentController.java
  src/main/java/com/i3/delivery/domain/payment/controller/PaymentCotroller.java
  src/main/java/com/i3/delivery/domain/payment/dto/PaymentRequestDto.java
  src/main/java/com/i3/delivery/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/i3/delivery/domain/payment/dto/PaymentStatusRequestDto.java
  src/main/java/com/i3/delivery/domain/payment/entity/Payment.java
  src/main/java/com/i3/delivery/domain/payment/entity/enums/PaymentStatusEnum.java
  src/main/java/com/i3/delivery/domain/payment/repository/PaymentRepository.java
  src/main/java/com/i3/delivery/domain/payment/service/PaymentService.java
Labels: enhancement

#30 Feat: 에러 처리 기능 구현
  src/main/java/com/i3/delivery/domain/category/service/CategoryService.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement

#32 Feature store
  src/main/java/com/i3/delivery/domain/category/service/CategoryService.java
  src/main/java/com/i3/delivery/domain/product/entity/Product.java
  src/main/java/com/i3/delivery/domain/product/service/ProductService.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement, refactor

#33 Feat : 장바구니 기반 주문 생성 기능 구현
  src/main/java/com/i3/delivery/domain/cart/entity/Cart.java
  src/main/java/com/i3/delivery/domain/order/controller/OrderController.java
  src/main/java/com/i3/delivery/domain/order/dto/request/OrderRequestDto.java
  src/main/java/com/i3/delivery/domain/order/dto/response/OrderListResponseDto.java
  src/main/java/com/i3/delivery/domain/order/dto/response/OrderResponseDto.java
  src/main/java/com/i3/delivery/domain/order/entity/Order.java
  src/main/java/com/i3/delivery/domain/order/service/OrderService.java
Labels: enhancement

#35 Feat: Store 상태변경 기능 구현 및
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreReviewMeta.java
  src/main/java/com/i3/delivery/domain/store/dto/StoreReviewResponsePage.java
  src/main/java/com/i3/delivery/domain/store/entity/Store.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
Labels: enhancement, refactor

#36 refactor: findAll 메서드 수정
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
Labels: refactor

#38 refactor: Store 조회 메서드 권한에 맞게 변경
  src/main/java/com/i3/delivery/domain/store/controller/StoreController.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/StoreRepositoryCustom.java
  src/main/java/com/i3/delivery/domain/store/repository/custom/impl/StoreRepositoryImpl.java
  src/main/java/com/i3/delivery/domain/store/service/StoreService.java
  src/main/java/com/i3/delivery/global/exception/common/ErrorCode.java
  src/main/java/com/i3/delivery/global/exception/store/NotStoreManagerOrMaster.java
  src/main/java/com/i3/delivery/global/exception/store/StoreDeletedException.java
  src/main/resources/db/data.sql
Labels: refactor
